import turtle

turtle.circle(25)
turtle.up()
turtle.right(90)
turtle.forward(25)
turtle.left(90)
turtle.down()
turtle.circle(50)
turtle.up()
turtle.forward(100)
turtle.down()
turtle.forward(200)
turtle.up()
turtle.forward(100)
turtle.down()
turtle.circle(50)
turtle.up()
turtle.left(90)
turtle.forward(25)
turtle.right(90)
turtle.down()
turtle.circle(25)
turtle.done()
